name: Pipeline Task
description: A task related to one of the 4 Core Pipelines
title: "[Pipeline]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: pipeline
    attributes:
      label: Pipeline
      description: Which core pipeline does this task belong to?
      options:
        - Archaeology
        - Documentation
        - Architecture
        - Re-implementation
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What should be accomplished?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests pass (pytest + behave)
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
      default: 1
